dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- export TZ=Brazil/East
deploy:
  provider: heroku
  api_key:
    - secure: "41c346a3-fe21-4e0f-a0f3-7ab85c9e147d"
  app: dmardegan-wallet-api
